/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jogo;

import javax.swing.JButton;
import javax.swing.JOptionPane;


/**
 *
 * @author Clênio
 */
public class JogodaVelha extends javax.swing.JFrame {

    /**
     * Creates new form JogodaVelha
     */
    boolean vez = true; //se vez igual true e a vez do jogador 1 e se vez igual false jogador2
    boolean vencedor = false;
    int qtdBotoesPressio = 0;
   
    
    public JogodaVelha() {
        initComponents();
        setResizable(false);
        
        
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jogador1 = new javax.swing.JTextField();
        jogador2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBjogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha");

        btn3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn3.setEnabled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn1.setEnabled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn4.setEnabled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn5.setEnabled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn6.setEnabled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn9.setEnabled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn7.setEnabled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btn8.setEnabled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel1.setText("Jogador 1:");

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel2.setText("Jogador 2:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Desenvolvido por Clênio Eduardo");

        jBjogar.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jBjogar.setText("Iniciar o Jogo");
        jBjogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBjogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jogador2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jBjogar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBjogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBjogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBjogarActionPerformed
        // TODO add your handling code here:
        if(!jogador1.getText().isEmpty() && !jogador2.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você começa jogando "+jogador1.getText()+"!","Iniciano o jogo",JOptionPane.INFORMATION_MESSAGE,null);
            jBjogar.setEnabled(false);
            abilitarBotoes(); //abilitando os botões do jogo
           
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos com os nomes dos jogadores", "Atenção", JOptionPane.ERROR_MESSAGE, null);
        }
        
    }//GEN-LAST:event_jBjogarActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn1);
        if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
        
        desabilitaBotao(btn1);
        verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn2);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn2);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn3);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn3);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn4);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn4);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn5);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn5);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn6);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn6);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn7);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn7);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn8);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn8);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        qtdBotoesPressio++;
        setaValorNoBotao(btn9);
         if(vez){
            vez = false;
        }
        else{
            vez = true;
        }
         desabilitaBotao(btn9);
         verificaGanhadorJogador1();
        verificaGanhadorJogador2();
        verificadeuVelha();
    }//GEN-LAST:event_btn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogodaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogodaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogodaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogodaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogodaVelha().setVisible(true);
            }
        });
        
        
    }
    
    public void desabilitaBotao(JButton botao){
        botao.setEnabled(false);
    }
    
    public void abilitarBotoes(){
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
    }
    
    public void setaValorNoBotao(JButton botao){
        if(vez){
            botao.setText("X");
        }
        else{
             botao.setText("O");
        }
    }
    
    public void verificaGanhadorJogador1(){
        if(btn1.getText().equals("X") && btn2.getText().equals("X")&& btn3.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
             finalizaJogo();
             inicializaJogo();
        }
        else if(btn1.getText().equals("X") && btn4.getText().equals("X")&& btn7.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn1.getText().equals("X") && btn5.getText().equals("X")&& btn9.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn3.getText().equals("X") && btn5.getText().equals("X")&& btn7.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn3.getText().equals("X") && btn6.getText().equals("X")&& btn9.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn2.getText().equals("X") && btn5.getText().equals("X")&& btn8.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn7.getText().equals("X") && btn8.getText().equals("X")&& btn9.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn4.getText().equals("X") && btn5.getText().equals("X")&& btn6.getText().equals("X")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador1.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
    }
   
    public void verificadeuVelha(){
        if(qtdBotoesPressio == 9 && vencedor == false){
            JOptionPane.showMessageDialog(rootPane, "Nenhum ganhador... ","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             finalizaJogo();
             inicializaJogo();
        }
        
    }
    
     public void verificaGanhadorJogador2(){
        if(btn1.getText().equals("O") && btn2.getText().equals("O")&& btn3.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn1.getText().equals("O") && btn4.getText().equals("O")&& btn7.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn1.getText().equals("O") && btn5.getText().equals("O")&& btn9.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn3.getText().equals("O") && btn5.getText().equals("O")&& btn7.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn3.getText().equals("O") && btn6.getText().equals("O")&& btn9.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn2.getText().equals("O") && btn5.getText().equals("O")&& btn8.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn7.getText().equals("O") && btn8.getText().equals("O")&& btn9.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
        else if(btn4.getText().equals("O") && btn5.getText().equals("O")&& btn6.getText().equals("O")){
             JOptionPane.showMessageDialog(rootPane, " Parabéns, Você ganhou "+jogador2.getText()+"!","FIM DE JOGO",JOptionPane.INFORMATION_MESSAGE,null);
             vencedor = true;
              finalizaJogo();
             inicializaJogo();
        }
    }
     
     public void inicializaJogo(){
         qtdBotoesPressio = 0;
         vez = true;
         vencedor = false;
          btn1.setText("");
          btn2.setText("");
          btn3.setText("");
          btn4.setText("");
          btn5.setText("");
          btn6.setText("");
          btn7.setText("");
          btn8.setText("");
          btn9.setText("");
          jBjogar.setEnabled(true);
          jogador1.setText("");
          jogador2.setText("");        
         
     }
     
     public void finalizaJogo(){
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
     }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton jBjogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jogador1;
    private javax.swing.JTextField jogador2;
    // End of variables declaration//GEN-END:variables
}
